### ISSUE TITLE
Integrate upstream test suite

### ISSUE THREAD

**Issue by jonashaag** [universal-ctags/python-ctags3#1]
I added a new test suite under the `tests/` directory; however I just noticed there's a test suite under `src/tests/`. Merge the two and integrate them into Travis.

**Comment by sbraz** [comment]
I'll do it :)

**Comment by jonashaag** [comment]
:+1:

**Comment by jonashaag** [comment]
I'll give you commit permissions in a sec

Edit: Done, feel free to do other improvements to the project if you want

**Comment by sbraz** [comment]
I wouldn't mind a bit of feedback on my changes first, I'm not really
experienced with tests.

**Comment by jonashaag** [comment]
Sure, you can still do a PR and gather some feedback
