### ISSUE TITLE
Move to universal-ctags

### ISSUE THREAD

**Issue by jonashaag** [universal-ctags/python-ctags3#14]
HI, again.

Not to force a person like you extracting readtags.c from the ctags repository when I change readtags.c, I made a separated repository for readtags.c spin-off'ed from the ctags repository.  Please, see https://github.com/universal-ctags/libreadtags .

I think python-ctags3 is not enough major for its great usefulness. Many people though tags file can be used via vim or editors. They don't know interesting command line based application like https://github.com/universal-ctags/ctags/issues/3043 . 

How do you think running this repo at Universal Ctags organization (https://github.com/universal-ctags) ?

universal-ctags becomes popular. So more people may visit the organization page and find python-ctags3.
It means you will find more bug reports but you may get contributions.

Note: even if you use readtags.c of the libreadtags, you can read a tags file generated by Exuberant Ctags.

I'm not good at English. So forgive me if I use impolite expressions.

_Originally posted by @masatake in https://github.com/jonashaag/python-ctags3/issues/7#issuecomment-857016635_

**Comment by jonashaag** [comment]
I think it would make sense to incorporate this project with your organisation but I'll let @jonashaag answer because I don't really use the project a lot.

_Originally posted by @sbraz in https://github.com/jonashaag/python-ctags3/issues/7#issuecomment-857050189_

**Comment by jonashaag** [comment]
Happy to transform to your organization and also transform maintenance to you if you want. Just to be sure, will libreadtags be backwards compatible with Exuberant ctags in the future?

_Originally posted by @jonashaag in https://github.com/jonashaag/python-ctags3/issues/7#issuecomment-857098183_

**Comment by jonashaag** [comment]
> Happy to transform to your organization and also transform maintenance to you if you want. 

Do you mean you will not maintain the repository after transformed?
I don't expect taking over the maintainership because my knowledge about Python is so limited.

> Just to be sure, will libreadtags be backwards compatible with Exuberant ctags in the future?

Yes.
libreadtags and u-ctags follow the tags file format explained in https://docs.ctags.io/en/latest/man/tags.5.html .
The tags.5.html is derived from a document file in Exuberant ctags source tree.
u-ctags project adds some exceptional rules to tags.5.html to support tags names including tab characters. libreadtags can handle it. Anyway libreadtags will be able to read tags files generated by Exuberant ctags in the future.

_Originally posted by @masatake in https://github.com/jonashaag/python-ctags3/issues/7#issuecomment-857146411_

**Comment by jonashaag** [comment]
> Do you mean you will not maintain the repository after transformed?
> I don't expect taking over the maintainership because my knowledge about Python is so limited.

OK, we can maintain it all together, @sbraz and me on the Python side of things and you can ping us whenever we should update something in the ctags impl.

I'd like to transfer, can you give me permissions to create a public repo in the orga?

_Originally posted by @jonashaag in https://github.com/jonashaag/python-ctags3/issues/7#issuecomment-857478126_

**Comment by masatake** [comment]
> OK, we can maintain it all together, @sbraz and me on the Python side of things and you can ping us whenever we should update something in the ctags impl.

Yes, it is what I expected.

I sent an invitation.
After transferring, I will adjust the access-right; I will assign admin or something right to you.

**Comment by masatake** [comment]
> I'd like to transfer, can you give me permissions to create a public repo in the orga?

I sent an invitation. Could you make a repository?

**Comment by jonashaag** [comment]
Worked!

**Comment by masatake** [comment]
Thank you!
I assigned the "Maintain" role of the new repository.

**Comment by jonashaag** [comment]
Great. If there are any changes to readtags etc. you want me to make feel free to post them now :)

**Comment by masatake** [comment]
I'm studying how we can improve libreadtags and python-ctags3.

I'm thinking about synchronizing the version of libreadtags and that of python-ctags3.
Give me some time.

BTW, I have a question (and a comment) about the name of this software.

I think python3-ctags is better than python-ctags3.

python3-foo is a popular convention at least on Fedora that I'm using.
```
$ yum search python3 | wc -l    
3551
$ yum search 'python-*3' | wc -l
18
```

python-ctags3 implies python binding for ctags version 3.

I'm thinking about the name more. 
ctags is a tags file generator.
There are tags generators other than ctags. e.g. gotags for GO language, hasktags for haskell, ripper-tags for Ruby.

The name python-ctags3 gives users impressions that  python-ctags3 supports only the output file generated by (u-)ctags or python-ctags3 is a library for running the ctags command for generating a tags file.

IMHO, python3-readtags is a better name representing what the software does till python4 is released:-P

On other hand, "ctags" is a popular name. It may be more catchy than readtags. So using "ctags" is understandable.

This is just an idea.

**Comment by masatake** [comment]
I found the name 'python-ctags3` is already referred to in your klaus. Changing the name of the software makes uesrs confused.
We should not change the name. Sorry for making noise.

**Comment by jonashaag** [comment]
I definitely agree that the name is unfortunate but I’m not sure if it’s worth changing it now.
