### ISSUE TITLE
No Clear documentation to fetch key-value pairs from python.

### ISSUE THREAD

**Issue by UtkarshBhatthere** [universal-ctags/python-ctags3#15]
> AllocBuffer	rpc/impl.c/^void  AllocBuffer(MESSAGE_BUFFER_S *const MsgBuffer, uint32_t opCode, $/;"	f	line:502	typeref:typename:void	end:516 <--------- This param

Here, I am interested in fetching the "end" parameter from the lines where it is present, but the python examples and documentation do not present any option to do so.

**Comment by UtkarshBhatthere** [comment]
Few random attempts and now I know, simple entry[b'key'] would be sufficient.

**Comment by jonashaag** [comment]
Is this something that's missing from the documentation? If so, mind to add it? :)
