### ISSUE TITLE
Merge py3 changes into master branch

### ISSUE THREAD

**Issue by sbraz** [universal-ctags/python-ctags3#3]
It's a bit unusual and could be confusing for users to have `py3` as default branch instead of `master`, don't you think?

**Comment by jonashaag** [comment]
As long as it's the only branch I think it's OK. I'm also fine with renaming it to `master` and the "old" master `upstream` or something.

**Comment by sbraz** [comment]
I have renamed py3 → master but i can't seem to remove the old py3 branch, can you do it? Also, could you upload a new release with the improved tests?

**Comment by jonashaag** [comment]
Done!
