### ISSUE TITLE
Release 1.2.2 containing the tests

### ISSUE THREAD

**Issue by sbraz** [universal-ctags/python-ctags3#4]
I've added the tests to MANIFEST.in, can you release this as 1.2.2?

**Comment by sbraz** [comment]
@jonashaag Hi Jonas, did you see my message?

**Comment by jonashaag** [comment]
Why would we want to release the tests?

**Comment by sbraz** [comment]
Gentoo and Debian need them. I'll provide more details later if you want me
to, but it's common practice to include them in the release tarball.

**Comment by sbraz** [comment]
Here are some examples: https://github.com/byroot/pysrt/pull/59/ or https://github.com/maxcountryman/flask-uploads/issues/2.

**Comment by jonashaag** [comment]
OK, released

**Comment by sbraz** [comment]
Dist seems to be missing the example file which I use for the tests. Let me see what the MANIFEST is missing.

**Comment by sbraz** [comment]
Are you OK with me doing this?

``` diff
diff --git a/MANIFEST.in b/MANIFEST.in
index 97d2e99..b1dbf1f 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -2,4 +2,5 @@ include README.md
 include src/_readtags.c
 include src/readtags.c
 include src/include/readtags.h
+include src/examples/*
 recursive-include tests *.py
```

**Comment by jonashaag** [comment]
Sure... maybe use recursive include there

**Comment by sbraz** [comment]
We'll have to release 1.2.3 though, PyPI won't let us overwrite the 1.2.2 tarball :/

**Comment by sbraz** [comment]
Ok it's ready to release: https://github.com/jonashaag/python-ctags3/commit/b0ba4356089a07cec1462f9279ceed7de66ca53e

**Comment by jonashaag** [comment]
Done
