### ISSUE TITLE
Back slash handling

### ISSUE THREAD

**Issue by masatake** [universal-ctags/python-ctags3#7]
Double backslashes at the end of pattern can crash readtags.c.

```
[yamato@x201]~/var/python-ctags3/src/examples% git diff tags            
diff --git a/src/examples/tags b/src/examples/tags
index 02ebfd5..70e5d33 100644
--- a/src/examples/tags
+++ b/src/examples/tags
@@ -281,7 +281,7 @@ file        ../include/readtags.h   /^      const char *file;$/;"   kind:member     line:112        languag
 file   ../include/readtags.h   /^      } file;$/;"     kind:member     line:72 language:C++    struct:__anon9  typeref:struct:__anon9::__anon11        access:public
 fileScope      ../include/readtags.h   /^      short fileScope;$/;"    kind:member     line:129        language:C++    struct:__anon14 access:public
 find   ../readtags.c   /^static tagResult find (tagFile *const file, tagEntry *const entry,$/;"        kind:function   line:649        language:C      file:   signature:(tagFile *const file, tagEntry *const entry, const char *const name, const int options)
-findBinary     ../readtags.c   /^static tagResult findBinary (tagFile *const file)$/;" kind:function   line:592        language:C      file:   signature:(tagFile *const file)
+findBinary     ../readtags.c   /^static tagResult findBinary (tagFile *const file)\\/;"        kind:function   line:592        language:C      file:   signature:(tagFile *const file)
 findFirstMatchBefore   ../readtags.c   /^static tagResult findFirstMatchBefore (tagFile *const file)$/;"       kind:function   line:577        language:C      file:   signature:(tagFile *const file)
 findFirstNonMatchBefore        ../readtags.c   /^static void findFirstNonMatchBefore (tagFile *const file)$/;" kind:function   line:559        language:C      file:   signature:(tagFile *const file)
 findNext       ../readtags.c   /^static tagResult findNext (tagFile *const file, tagEntry *const entry)$/;"    kind:function   line:689        language:C      file:   signature:(tagFile *const file, tagEntry *const entry)
[yamato@x201]~/var/python-ctags3/src/examples% python ./example.py tags
Exuberant Ctags
Darren Hiebert
2
DL_EXPORT
macro
found
649
/^static tagResult find (tagFile *const file, tagEntry *const entry,$/
function
zsh: segmentation fault (core dumped)  python ./example.py tags
```

This is spotted at universal-ctags project(http://ctags.io) and I fixed this bug.
If this bug is reproduced in python-ctags3, could you consider to cherry-pick https://github.com/universal-ctags/ctags/pull/686/commits/42d50f3b2b424e2ef96249910fe13dbf15aa7cae ?

**Comment by jonashaag** [comment]
Thanks for the report. I'm not very well educated in terms of what ctags implementations exist. So far I've only ever used Exuberant ctags. Is it abandoned? What maintained alternatives exist? Where is universal-ctags included (distros etc)?

**Comment by masatake** [comment]
The development of Exuberant ctags is inactive. See https://sourceforge.net/p/ctags/mailman/ctags-devel/
Universal ctags is a project forked from Exuberant ctags(http://docs.ctags.io/en/latest/). I am one of the developers of the project.
As far as I know Universal-ctags is the most active in the alternatives. See http://docs.ctags.io/en/latest/news.html about what we have done since forked from Exuberant ctags.

However, I opened this issue not for advertising Universal-ctags. (Of course, I'm happy if you get interest in it:-) The issue itself is nothing to do with ctags implementations. It is an issue of readtags side. As you may know, the implementations of readtags and ctags are well separated with tags file format.

**Comment by jonashaag** [comment]
> As you may know, the implementations of readtags and ctags are well separated with tags file format.

I did not know that, and it doesn't really make sense to me, since your readtags change has been committed to your ctags fork, so they're not separated entirely? The key question for me is which version of readtags we can rely on here, i.e. which one is going to be maintained in the future. This is also why I asked if universal ctags has been included somewhere already, because as an outsider to the ctags world I can't judge which is the "better" ctags implementation.

**Comment by masatake** [comment]
> The key question for me is which version of readtags we can rely on here, i.e. which one is going to be maintained in the future. This is also why I asked if universal ctags has been included somewhere already, because as an outsider to the ctags world I can't judge which is the "better" ctags implementation.

I think there is no reliable one. Universal-ctags is actively maintained but not released yet. Only advanced users use it. Exuberant-ctags is not actively maintained but is used widely.  

However, is the choice of upstream really important in this case? Basically I think readtags.c is stable enough. Maybe the bug I reported here is the last serious bug. So just applying my patch is enough.
Even if I found a critical one and fixed it, I will report here, the most actively developed python-ctags implementation.

BTW,  I'm a developer of universal-ctags. In other hand I'm a user of python-ctags.
There are many python-ctags forks. I would like to fix the bug I reported here. Do I have to report this to all the forked projects? Which fork of python-ctags project I should contribute and report to?

**Comment by jonashaag** [comment]
OK, thanks for the explanation. I'll merge the change then. Do you have the time to make pull request? A comment at the top of all readtags files that we are using universal-ctags' readtags and  a link to the website/GitHub repo would be great.

I've had a look at the Python package manager repo. There are only two released versions of python-ctags; one is unmaintained and the other is this. https://pypi.python.org/pypi?%3Aaction=search&term=ctags&submit=search

**Comment by masatake** [comment]
O.K. I will make a pull request.

> I've had a look at the Python package manager repo. There are only two released versions of python-ctags; one is unmaintained and the other is this. https://pypi.python.org/pypi?%3Aaction=search&term=ctags&submit=search

Oh, thank you. I will report this bug to https://github.com/hddmet/python-ctags next.

**Comment by masatake** [comment]
HI, again.

Not to force a person like you extracting readtags.c from the ctags repository when I change readtags.c, I made a separated repository for readtags.c spin-off'ed from the ctags repository.  Please, see https://github.com/universal-ctags/libreadtags .

I think python-ctags3 is not enough major for its great usefulness. Many people though tags file can be used via vim or editors. They don't know interesting command line based application like https://github.com/universal-ctags/ctags/issues/3043 . 

How do you think running this repo at Universal Ctags organization (https://github.com/universal-ctags) ?

universal-ctags becomes popular. So more people may visit the organization page and find python-ctags3.
It means you will find more bug reports but you may get contributions.

Note: even if you use readtags.c of the libreadtags, you can read a tags file generated by Exuberant Ctags.

I'm not good at English. So forgive me if I use impolite expressions.

**Comment by sbraz** [comment]
I think it would make sense to incorporate this project with your organisation but I'll let @jonashaag answer because I don't really use the project a lot.

**Comment by jonashaag** [comment]
Happy to transform to your organization and also transform maintenance to you if you want. Just to be sure, will libreadtags be backwards compatible with Exuberant ctags in the future?

**Comment by masatake** [comment]
> Happy to transform to your organization and also transform maintenance to you if you want. 

Do you mean you will not maintain the repository after transformed?
I don't expect taking over the maintainership because my knowledge about Python is so limited.

> Just to be sure, will libreadtags be backwards compatible with Exuberant ctags in the future?

Yes.
libreadtags and u-ctags follow the tags file format explained in https://docs.ctags.io/en/latest/man/tags.5.html .
The tags.5.html is derived from a document file in Exuberant ctags source tree.
u-ctags project adds some exceptional rules to tags.5.html to support tags names including tab characters. libreadtags can handle it. Anyway libreadtags will be able to read tags files generated by Exuberant ctags in the future.

**Comment by jonashaag** [comment]
> Do you mean you will not maintain the repository after transformed?
> I don't expect taking over the maintainership because my knowledge about Python is so limited.

OK, we can maintain it all together, @sbraz and me on the Python side of things and you can ping us whenever we should update something in the ctags impl.

I'd like to transfer, can you give me permissions to create a public repo in the orga?

**Comment by jonashaag** [comment]
Let's move discussion to #14
