### ISSUE TITLE
SegFault on OSX

### ISSUE THREAD

**Issue by jonwilson030981** [universal-ctags/python-ctags3#9]
First, many thanks for maintaining this library, it is proving very useful for the application I am developing. I have had a few issues with the library when running on OSX though. I am using the linux kernel 4.4.0 source as test data and it had issues when processing the tags of drivers/dma/at_hdma.c. I have narrowed it down to a single line in the tag file which I have attached below (that's not to say that other lines don't suffer the same fate). The issue only appears to affect the library when installed using pip3 (installing version v1.2.3), the issue is not present when installed using the makefile from cloning the git repository.

The segfault occurs inside the strncmp call in parseTagLine. Comparing the function in v1.2.3 and the head, it looks like the logic has been changed to use a new function countContinuousBackslashesBackward. Are there plans to release a new version containing this fix which can be installed using pip3 rather than by cloning the repo? Is there any errata to which this defective edge case could be added so that others can quickly identify should they encounter the same problem?

[test.txt](https://github.com/jonashaag/python-ctags3/files/961388/test.txt)

**Comment by jonashaag** [comment]
Hey, thanks for the report. It seems I simply forgot about these changes. I just released 1.2.4. Please let me know if this version works for you and fixes the issues?

**Comment by jonwilson030981** [comment]
Hi Jonas,

Thanks for the quick response. Sorry for the delay in getting back to you, I’ve had a bit of a busy week. I haven’t had chance to run it on a big sample yet to check for any regressions, but that change seems to have fixed the issue I was having.

Thanks for sorting it so quickly, I’ll get back to you if I have any further issues.

Kind Regards

Jon
